monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - dom_first_form
        - dom_second_form
        - migration_dom
        - migration_personnel_delete
        - migration_user_delete
        - migration_dom_delete
        - migration_personnel
        - migration_user
        - migration_badm_delete

    handlers:
        dom_first:
            type: stream
            path: "%kernel.logs_dir%/dom_first_form.log"
            level: debug
            channels: [dom_first_form]
            formatter: monolog.formatter.user_log
        dom_second:
            type: stream
            path: "%kernel.logs_dir%/dom_second_form.log"
            level: debug
            channels: [dom_second_form]
            formatter: monolog.formatter.user_log
        migration_dom:
            type: stream
            path: "%kernel.logs_dir%/migrations/migration_dom.log"
            level: info
            channels: [migration_dom]
        migration_personnel:
            type: stream
            path: "%kernel.logs_dir%/migrations/migration_personnel.log"
            level: info
            channels: [migration_personnel]
        migration_user:
            type: stream
            path: "%kernel.logs_dir%/migrations/migration_user.log"
            level: info
            channels: [migration_user]
        migration_personnel_delete:
            type: stream
            path: "%kernel.logs_dir%/migrations/delete_personnel.log"
            level: info
            channels: [migration_personnel_delete]
        migration_user_delete:
            type: stream
            path: "%kernel.logs_dir%/migrations/delete_user.log"
            level: info
            channels: [migration_user_delete]
        migration_dom_delete:
            type: stream
            path: "%kernel.logs_dir%/migrations/delete_dom.log"
            level: info
            channels: [migration_dom_delete]
        migration_badm_delete:
            type: stream
            path: "%kernel.logs_dir%/migrations/delete_badm.log"
            level: info
            channels: [migration_badm_delete]

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!migration_dom", "!migration_personnel", "!migration_user", "!migration_personnel_delete", "!migration_user_delete", "!migration_dom_delete", "!migration_badm_delete"]
            # uncomment to get logging in your browser
            # you may have to allow bigger header sizes in your Web server configuration
            #firephp:
            #    type: firephp
            #    level: info
            #chromephp:
            #    type: chromephp
            #    level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console", "!migration_dom", "!migration_personnel", "!migration_user", "!migration_personnel_delete", "!migration_user_delete", "!migration_dom_delete", "!migration_badm_delete"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            # Utilisation du NotifierHandler pour l'environnement de test (coh√©rent avec la prod)
            notifier_test:
                type: service
                id: App\Logger\NotifierHandler
                level: error
                channels: ["!event"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
            notifier:
                type: service
                id: App\Logger\NotifierHandler
                level: error
                channels: [ "!event" ]
