when@dev:
    doctrine:
        dbal:
            default_connection: default
            connections:
                default:
                    # Active le logging SQL détaillé en dev
                    logging: false
                    profiling: false
                    profiling_collect_backtrace: false
        orm:
            auto_generate_proxy_classes: true
